server:
  port: 8585

spring:
  application:
    name: wigell-travels

pricing:
  base-url: ${PRICING_BASE_URL:http://localhost:8787}
  username: ${PRICING_USERNAME:Courtney}
  password: ${PRICING_PASSWORD:Love}
